name: Generate and Commit File

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install any dependencies, if needed

      - name: Run Python script to generate file
        run: |
          python generate_file.py  # Replace with your script that generates the file

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Stage, commit, and push changes
        run: |
          git add versioned_file.txt  # The file generated/modified by the Python script
          git commit -m "Update versioned file"
          git push
        env:
          # Use GitHub's token to authenticate
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
